apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: api
          image: registry.digitalocean.com/carbon-server/user:0.5
          ports:
            - containerPort: 5000
          env:
            - name: DB_CONNECTION
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_CONNECTION
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  ports:
    - port: 80
      name: http
      targetPort: 5000
  selector:
    app: user
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: user
  namespace: default
  annotations:
    konghq.com/methods: 'GET,POST'
    konghq.com/plugins: carbon-auth

spec:
  ingressClassName: kong
  rules:
    - http:
        paths:
          - path: /api/users
            pathType: Prefix
            backend:
              service:
                name: user-service
                port:
                  number: 80
